### ISSUE TITLE
Adding English Language Support (english l18n)

### ISSUE THREAD

**Issue by casprussian** [codex-studio/nav#10]
Why is codex.studio in English, and the GitHub discussion in English, if the website is all in Chinese? Shouldn't there be either: 

1) English version (use a locale package, meaning the spots were there could be either english or chinese, would be variable placeholder which would point to a value in the locale package, and would be chosen depending on main language guessed by IP or chosen by button at top.)

2) Dual English/Chinese labels, each button/text would have two languages side by side.

3) Something else??

**Comment by mj66** [comment]
1) It is really NOT THAT EASY to scan your physical address only by ip. Locale is a good idea and I will work on it.
2) Same problem. No such space. Or if i have two languages, which one should be bigger?

**Comment by mj66** [comment]
@casprussian By the way, if you want to use english language you can still use ver 0.1.0 locally with php installed on your pc

**Comment by casprussian** [comment]
But I wanna use the latest version weh!
你喺唔喺racist嗎！

**Comment by mj66** [comment]
Updated version 1.1.0 (currently in beta branch if you didn't notice) will go live 8 PM EST tomorrow 4/12. Thrre will be a maintainance break to clean up server dump.

**Comment by mj66** [comment]
Updated. See beta branch.

**Comment by casprussian** [comment]
Where can I find the beta branch?
