### ISSUE TITLE
Animations are not fluent on WP devices on Edge

### ISSUE THREAD

**Issue by liangyiliang** [codex-studio/nav#14]
Hi all,
I realize a bug in CodEX Nav in which the tab-extending animation is slow and not fluent on Microsoft EDGE on Windows 10 Mobile. Please try to fix it, thanks. 
Leo
Onewindows@codex.studio

**Comment by mj66** [comment]
Issue identified. Will fix before closure of 7/25

**Comment by mj66** [comment]
Edge and I based browser have weak support on animations. However, we would try to make a simplified version for weaker browsers.
