### ISSUE TITLE
Clock at top takes a second to load.

### ISSUE THREAD

**Issue by casprussian** [codex-studio/nav#7]
On Chromium Version 37.0.2062.120 Built on Debian 7.6, running on Debian 7.0 (281580) (64-bit):

Clock loads after the rest of the page.

**Comment by mj66** [comment]
Issue noticed. Please check back for later builds, hopefully by Tuesday after July 4th break.

**Comment by mj66** [comment]
Fixed on [Commit 1d93aee5c17eaa1931583f8ecd526a5363ae4f6a](https://github.com/codex-studio/nav/commit/1d93aee5c17eaa1931583f8ecd526a5363ae4f6a)
